# docker-compose.yml
version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: ugene_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-ugene_workflows}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - ugene_network

  # Redis Queue
  redis:
    image: redis:7-alpine
    container_name: ugene_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ugene_network

  # UGENE SDK Docker Image
  ugene_sdk:
    build:
      context: ./ugene-sdk
      dockerfile: Dockerfile
    image: ugene_sdk_docker_image
    container_name: ugene_sdk_container
    volumes:
      - ugene_workdir:/tmp/ugene_workdir
      - ./data:/data
    networks:
      - ugene_network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ugene_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - MONGODB_URL=mongodb://${MONGO_USER:-admin}:${MONGO_PASSWORD:-password123}@mongodb:27017
      - REDIS_URL=redis://redis:6379
      - DATABASE_NAME=${MONGO_DB:-ugene_workflows}
      - UPLOAD_DIR=/app/uploads
      - UGENE_WORKDIR=/tmp/ugene_workdir
    volumes:
      - ./backend:/app
      - ugene_workdir:/tmp/ugene_workdir
      - upload_storage:/app/uploads
      - ./data:/app/data
    depends_on:
      - mongodb
      - redis
      - ugene_sdk
    networks:
      - ugene_network

  # RQ Worker for Background Tasks
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    container_name: ugene_worker
    restart: always
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - MONGODB_URL=mongodb://${MONGO_USER:-admin}:${MONGO_PASSWORD:-password123}@mongodb:27017
      - REDIS_URL=redis://redis:6379
      - DATABASE_NAME=${MONGO_DB:-ugene_workflows}
      - UGENE_WORKDIR=/tmp/ugene_workdir
    volumes:
      - ./backend:/app
      - ugene_workdir:/tmp/ugene_workdir
      - upload_storage:/app/uploads
      - ./data:/app/data
    depends_on:
      - mongodb
      - redis
      - ugene_sdk
    networks:
      - ugene_network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:8000
    container_name: ugene_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ugene_network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: ugene_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - ugene_network

volumes:
  mongodb_data:
  redis_data:
  ugene_workdir:
  upload_storage:

networks:
  ugene_network:
    driver: bridge

