---

# docker-compose.override.yml - Development overrides (fixed)
services:
  # Development-specific overrides
  backend:
    environment:
      - ENVIRONMENT=development
      - RELOAD=true
      - LOG_LEVEL=debug
      - INIT_DATABASE=true
    volumes:
      - ./backend:/app
      - /app/__pycache__

  frontend:
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000/ws
    volumes:
      - ./frontend:/app
      - /app/node_modules

  worker:
    environment:
      - LOG_LEVEL=debug
    volumes:
      - ./backend:/app
      - /app/__pycache__


